import Header from '@/components/header'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer'
import ModeToggleButton from '@/components/modeToggleButton';
// import { createGlobalStyle } from 'styled-components'

import { Providers } from '@/components/provider';

const inter = Inter({ subsets: ['latin'] })

// const GlobalStyle = createGlobalStyle`
//   :root {
//     --fg: #000;
//     --bg: #fff;
//   }

//   [data-theme="dark"] {
//     --fg: #fff;
//     --bg: #000;
//   }
// `

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {/* <GlobalStyle /> */}
        <Providers>
          <Header/>
          {children}
          {/* <Footer/> */}
        </Providers>
      </body>
    </html>
  )
}
